const express = require('express');
const router = express.Router();
const Center = require('../models/Center');

// GET all centres
router.get('/', async (req, res) => {
  try {
    const centers = await Center.find();
    res.json(centers);
  } catch (err) {
    console.error("Error fetching centers:", err);
    res.status(500).json({ message: err.message });
  }
});

// POST new centre (admin only)
router.post('/', async (req, res) => {
  const { name, address, phoneNumber } = req.body;
  console.log("Received center data:", req.body);
  try {
    // Validate required fields
    if (!name || !address || !phoneNumber) {
      return res.status(400).json({ message: 'All fields are required.' });
    }
    // Check for duplicate center by name
    const existing = await Center.findOne({ name: name.trim() });
    if (existing) {
      return res.status(400).json({ message: 'A center with this name already exists.' });
    }
    // Create new center (code will be auto-generated by the pre-save hook)
    const newCenter = new Center({ name, address, phoneNumber });
    await newCenter.save();
    res.status(201).json({ message: 'Centre added successfully', center: newCenter });
  } catch (err) {
    console.error("Error in POST /api/center-form:", err);
    res.status(500).json({ message: err.message });
  }
});

// PUT update center by ID
router.put('/:id', async (req, res) => {
  const { name, address, phoneNumber } = req.body;
  try {
    // Validate required fields
    if (!name || !address || !phoneNumber) {
      return res.status(400).json({ message: 'All fields are required.' });
    }
    // Check for duplicate center (by name only, since code is auto-generated)
    const existing = await Center.findOne({
      _id: { $ne: req.params.id },
      name: name.trim()
    });
    if (existing) {
      return res.status(400).json({ message: 'A center with this name already exists.' });
    }
    // Update center (do not modify auto-generated code)
    const updated = await Center.findByIdAndUpdate(
      req.params.id,
      { name, address, phoneNumber },
      { new: true }
    );
    if (!updated) {
      return res.status(404).json({ message: 'Center not found.' });
    }
    res.json({ message: 'Center updated successfully', center: updated });
  } catch (err) {
    console.error("Error in PUT /api/center-form:", err);
    res.status(500).json({ message: err.message });
  }
});

// DELETE center by ID
router.delete('/:id', async (req, res) => {
  try {
    const removed = await Center.findByIdAndDelete(req.params.id);
    if (!removed) {
      return res.status(404).json({ message: 'Center not found.' });
    }
    res.json({ message: 'Center deleted successfully' });
  } catch (err) {
    console.error("Error in DELETE /api/center-form:", err);
    res.status(500).json({ message: err.message });
  }
});

module.exports = router;
